data:
  root_path: ./data
  data_file: trading/XAUUSD_M15.csv
  batch_size: 32
  pin_mem: true
  num_workers: 4
  window_size: 20
  segment_size: 5
  num_features: 6
mask:
  ratio:
    - 0.4
    - 0.6
  window_size: 20
  segment_size: 5
meta:
  use_bfloat16: false
  load_checkpoint: false
  checkpoint_path: null
  copy_data: false
optimization:
  ema:
    - 0.996
    - 1.0
  epochs: 10
  weight_decay: 0.0001
  final_weight_decay: 0.0001
  warmup: 0
  start_lr: 0.001
  lr: 0.001
  final_lr: 0.0001
logging:
  folder: ./logs
  write_tag: ijepa_time_series
  log_freq: 10
  checkpoint_freq: 1